# Be careful with indent in beginning of line!

Logitech G413 keyboard:
    # In section - any name of your device you like.
    device: /dev/input/event3

    ## EXAMPLE OF SUBSECTION
    ## This is CTRL+R for example
    #
    # KEY_LEFTCTRL KEY_R:
    # inject_keys=KEY_RIGHTCTRL KEY_W
    # retranslate=False
    # run_command=ls -la

    KEY_KP6:
        plugin: gnome
        command: raise_or_run opera Opera

    KEY_KPPLUS:
        # In subsection - keys, must be handled
        # And what we must do with it below.
        inject_keys: KEY_RIGHTCTRL KEY_W


Logitech G602 mouse:
    device: /dev/input/event9

    KEY_LEFTSHIFT KEY_F8:
        inject_keys: KEY_RIGHTCTRL KEY_W

    ALT KEY_PAGEUP:
        inject_keys: KEY_LEFT

    ALT KEY_PAGEDOWN:
        inject_keys: KEY_RIGHT

Razer Nostromo:
    device: /dev/input/event6

    KEY_RIGHTSHIFT KEY_F6:
        inject_keys: KEY_R

    # KEY_TAB (01)
    # KEY_Q (02)
    # KEY_W (03)
    # KEY_E (04)
    # KEY_R (05)

    # KEY_CAPSLOCK (06)
    # KEY_A (07)
    # KEY_S (08)
    # KEY_D (09)
    # KEY_F (10)

    # KEY_LEFTSHIFT (11)
    # KEY_Z (12)
    # KEY_X (13)
    # KEY_C (14)

    # KEY_SPACE (15)

    # KEY_LEFTALT (above joystick)

    # Joystick:
    # KEY_DOWN
    # KEY_RIGHT
    # KEY_UP
    # KEY_LEFT
