Logitech G710 keyboard:
    # In section - any name of your device you like.
    device: /dev/input/event21

    ## EXAMPLE OF SUBSECTION
    ## This is CTRL+R for example
    #
    # KEY_LEFTCTRL KEY_R:
    # inject_keys=KEY_RIGHTCTRL KEY_W
    # retranslate=False
    # run_command=ls -la

    KEY_KP0:
        plugin: gnome
        command: minimize

    KEY_KPENTER:
        plugin: gnome
        command: close

    KEY_KP6:
        plugin: gnome
        command: raise opera Opera

    KEY_KPPLUS:
        # In subsection - keys, must be handled
        # And what we must do with it below.
        inject_keys: KEY_RIGHTCTRL KEY_W


Logitech G600 mouse:
    # This is second mouse device, as keyboard
    device: /dev/input/event5

    KEY_RIGHTSHIFT KEY_F6:
        inject_keys: KEY_R
