Logitech G710 keyboard:
    # In section - any name of your device you like.
    device: /dev/input/event6

    ## EXAMPLE OF SUBSECTION
    ## This is CTRL+R for example
    #
    # KEY_LEFTCTRL KEY_R:
    # inject_keys=KEY_RIGHTCTRL KEY_W
    # retranslate=False
    # run_command=ls -la

    KEY_KPPLUS:
        # In subsection - keys, must be handled
        # And what we must do with it below.
        inject_keys: KEY_RIGHTCTRL KEY_W


Logitech G600 mouse:
    # This is second mouse device, as keyboard
    device: /dev/input/event22

    KEY_RIGHTSHIFT KEY_F6:
        inject_keys: KEY_R
