
  KEY_SCROLLLOCK:
    command: flameshot gui

  KEY_PAUSE:
    plugin: gnome
    command: lock
    
  CTRL KEY_PAUSE:
    command: systemctl suspend



  KEY_KPSLASH:
#    command: amixer -q sset Master 5%-
    inject_keys: KEY_VOLUMEDOWN

  KEY_KPASTERISK:
#    command: amixer -q sset Master 5%+
    inject_keys: KEY_VOLUMEUP



  KEY_KPMINUS:
    # inject_keys: KEY_RIGHTMETA KEY_S
    inject_keys: KEY_LEFTMETA


  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W



  KEY_KP7:
    plugin: gnome
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop

  KEY_KP8:
    plugin: gnome
    # Special, to raise all Chromium-browser window
    # command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    # command: raise chromium chromium.Chromium
    # command: raise vivaldi-stable Vivaldi-stable
    command: raise firefox Firefox
    #command: raise_all firefox Navigator.Firefox https://www.youtube.com
    #command: raise opera Opera
  #KEY_LEFTCTRL KEY_KP8:
  CTRL KEY_KP8:
    plugin: gnome
    # Raise only Firefox with youtube player
    command: raise chromium-browser chromium.Chromium
    # command: raise echo Navigator.Firefox YouTube
    # command: raise firefox Navigator.Firefox
    # YouTube - Mozilla Firefox

  KEY_KP9:
    plugin: gnome
    command: raise pycharm jetbrains-pycharm
    # command: raise wing7.0 N/A Wing
  CTRL KEY_KP9:
    plugin: gnome
    command: raise /opt/sublime_text/sublime_text Sublime_text
  ALT KEY_KP9:
    plugin: gnome
    command: raise inkscape Inkscape
    # command: raise wing-personal6.1 N/A Wing
  # SHIFT KEY_KP9:
  #   plugin: gnome
  #   command: raise /opt/sublime_text/sublime_text sublime_text.Sublime_text
  META KEY_KP9:
    plugin: gnome
    command: raise atom atom.Atom



  KEY_KP4:
    plugin: gnome
    command: raise skype Skype

  KEY_KP5:
    plugin: gnome
    command: raise gnome-control-center gnome-control-center

  KEY_KP6:
    plugin: gnome
    #command: raise okular okular
    command: raise teams Teams

  CTRL KEY_KP6:
    plugin: gnome
    command: raise goldendict GoldenDict

#  KEY_RIGHTCTRL KEY_KP6:
#    plugin: gnome
#    command: raise goldendict goldendict.GoldenDict




  KEY_KP1:
    plugin: gnome
    # command: raise relanotes Relanotes
    command: raise relanotes python3 Relanotes
  CTRL KEY_KP1:
    plugin: gnome
    command: raise relacalc python3 RelaCalc
#  KEY_RIGHTCTRL KEY_KP1:
#    plugin: gnome
#    command: raise relacalc Relacalc

  KEY_KP2:
    plugin: gnome
    command: raise gnome-terminal Gnome-terminal

  KEY_KP3:
    plugin: gnome
    command: raise nautilus org.gnome.Nautilus




  KEY_KP0:
    plugin: gnome
    command: minimize

  KEY_KPDOT:
    plugin: gnome
    command: raise gedit gedit
    # command: raise /opt/sublime_text/sublime_text Sublime_text


  KEY_KPENTER:
    plugin: gnome
    command: close

