
#  META KEY_S:
#    #inject_keys: KEY_LEFTCTRL KEY_LEFTALT KEY_DOWN
#    plugin: wmctrl
#    command: raise thunar Thunar.Thunar

  # KEY_LEFTMETA: 
  #   inject_keys: KEY_LEFTCTRL KEY_F9


  KEY_SCROLLLOCK:
    command: flameshot gui

  KEY_PAUSE:
    inject_keys: KEY_LEFTCTRL KEY_LEFTALT KEY_L
  CTRL KEY_PAUSE:
    command: systemctl suspend -i


  KEY_KP7:
    plugin: wmctrl
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop

  KEY_KP8:
    plugin: wmctrl
    # Special, to raise all Chromium-browser window
    #command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    # command: raise chromium chromium.Chromium
    # command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable
    command: raise firefox Navigator.Firefox
    #command: raise_all firefox Navigator.Firefox https://www.youtube.com
    #command: raise opera Opera
  #KEY_LEFTCTRL KEY_KP8:
  CTRL KEY_KP8:
    plugin: wmctrl
    # Raise only Firefox with youtube player
    command: raise chromium-browser chromium.Chromium
    # command: raise echo Navigator.Firefox YouTube
    # command: raise firefox Navigator.Firefox
    # YouTube - Mozilla Firefox

  KEY_KP9:
    plugin: wmctrl
    command: raise pycharm jetbrains-pycharm
    # command: raise wing7.0 N/A Wing
  CTRL KEY_KP9:
    plugin: wmctrl
    command: raise /opt/sublime_text/sublime_text sublime_text.Sublime_text
  ALT KEY_KP9:
    plugin: wmctrl
    command: raise inkscape inkscape.Inkscape
    # command: raise wing-personal6.1 N/A Wing
  # SHIFT KEY_KP9:
  #   plugin: wmctrl
  #   command: raise /opt/sublime_text/sublime_text sublime_text.Sublime_text
  META KEY_KP9:
    plugin: wmctrl
    command: raise atom atom.Atom


  KEY_KP4:
    plugin: wmctrl
    command: raise skype skype.Skype

  KEY_KP5:
    plugin: wmctrl
    command: raise systemsettings5 systemsettings5.systemsettings

  KEY_KP6:
    plugin: wmctrl
    command: raise okular okular.okular
  CTRL KEY_KP6:
    plugin: wmctrl
    command: raise goldendict goldendict.GoldenDict
#  KEY_RIGHTCTRL KEY_KP6:
#    plugin: wmctrl
#    command: raise goldendict goldendict.GoldenDict




  KEY_KP1:
    plugin: wmctrl
    command: raise relanotes relanotes.py.Relanotes
  CTRL KEY_KP1:
    plugin: wmctrl
    command: raise relacalc relacalc.py.relacalc.py
#  KEY_RIGHTCTRL KEY_KP1:
#    plugin: wmctrl
#    command: raise relacalc Relacalc

  KEY_KP2:
    plugin: wmctrl
    command: raise konsole konsole.konsole

  KEY_KP3:
    plugin: wmctrl
    command: raise dolphin dolphin.dolphin


  KEY_KPDOT:
    plugin: wmctrl
    # command: raise kate kate.kate
    command: raise kwrite kwrite.kwrite


  KEY_KPSLASH:
#    command: amixer -q sset Master 5%-
    inject_keys: KEY_VOLUMEDOWN

  KEY_KPASTERISK:
#    command: amixer -q sset Master 5%+
    inject_keys: KEY_VOLUMEUP



  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W

  KEY_KP0:
    plugin: xdotool
    command: minimize

  KEY_KPENTER:
    plugin: wmctrl
    command: close

  KEY_KPMINUS:
    #command: xfdesktop --windowlist
    inject_keys: KEY_LEFTCTRL KEY_F9


