Logitech G710 keyboard:
  device: /dev/input/event9

  KEY_SCROLLLOCK:
    command: flameshot gui

  KEY_PAUSE:
    command: cinnamon-screensaver-command -l
    # to lock and disable moinitor:
    # cinnamon-screensaver-command -l; xset dpms force off;
  KEY_LEFTCTRL KEY_PAUSE:
    command: systemctl suspend -i
  KEY_RIGHTCTRL KEY_PAUSE:
    command: systemctl suspend -i


  KEY_KP7:
    plugin: wmctrl
    command: raise telegram-desktop TelegramDesktop

  KEY_KP8:
    plugin: wmctrl
    command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable
    #command: raise firefox Navigator.Firefox
    #command: raise opera Opera

  KEY_KP9:
    plugin: wmctrl
    command: raise pycharm jetbrains-pycharm


  KEY_KP4:
    plugin: wmctrl
    command: raise skype Skype

  KEY_KP5:
    plugin: wmctrl
    command: raise cinnamon-settings cinnamon-settings

  KEY_KP6:
    plugin: wmctrl
    command: raise okular Okular



  KEY_KP1:
    plugin: wmctrl
    command: raise relanotes Relanotes
  KEY_LEFTCTRL KEY_KP1:
    plugin: wmctrl
    command: raise relacalc Relacalc
  KEY_RIGHTCTRL KEY_KP1:
    plugin: wmctrl
    command: raise relacalc Relacalc

  KEY_KP2:
    plugin: wmctrl
    command: raise gnome-terminal Gnome-terminal

  KEY_KP3:
    plugin: wmctrl
    command: raise nemo nemo.Nemo


  KEY_KPDOT:
    plugin: wmctrl
    command: raise xed Xed


  KEY_KPSLASH:
    command: amixer -c 1 sset Master 5%-

  KEY_KPASTERISK:
    command: amixer -c 1 sset Master 5%+



  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W


  KEY_KP0:
    plugin: xdotool
    command: minimize

  KEY_KPENTER:
    plugin: wmctrl
    command: close

  KEY_KPMINUS:
    inject_keys: KEY_RIGHTMETA KEY_S



Logitech G600 mouse:
  device: /dev/input/event8

  KEY_LEFTMETA KEY_H:
    plugin: xdotool
    command: minimize

  # G4
  KEY_LEFTSHIFT KEY_F4:
    plugin: xdotool
    command: minimize
  # G7
  ALT KEY_LEFTMETA KEY_S:
    command: notify-send Alt+Meta+S


  # G5
  KEY_LEFTSHIFT KEY_F5:
    plugin: wmctrl
    command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable
    #command: raise firefox Navigator.Firefox
    #command: raise opera Opera
  # G8
  KEY_LEFTSHIFT KEY_F8:
    inject_keys: KEY_RIGHTCTRL KEY_W


  # G6
  KEY_LEFTSHIFT KEY_F6:
    plugin: wmctrl
    command: raise telegram-desktop TelegramDesktop
  # G9
  KEY_LEFTSHIFT KEY_F9:
    plugin: wmctrl
    command: raise skypeforlinux Skype


  # G10
  ALT KEY_PAGEUP:
    inject_keys: KEY_RIGHTALT KEY_LEFT
  SHIFT KEY_PAGEUP:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_HOME
  # G11
  ALT KEY_PAGEDOWN:
    inject_keys: KEY_RIGHTALT KEY_RIGHT
  SHIFT KEY_PAGEDOWN:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_END




