# Be careful with indent in beginning of line!
#
# One KEY defining block limited to 1024 bytes
#
# In section - any name of your device you like.
## EXAMPLE OF SUBSECTION
## This is CTRL+R for example
#
# KEY_LEFTCTRL KEY_R:
# inject_keys=KEY_RIGHTCTRL KEY_W
# run_command=ls -la


Logitech G710 Keyboard:
  #device: /dev/input/event9
  name: Logitech Logitech G710 Keyboard
  capabilities: keyboard


  KEY_SCROLLLOCK:
    command: flameshot gui

  KEY_PAUSE:
    plugin: gnome
    command: lock
  CTRL KEY_PAUSE:
    command: systemctl suspend



  KEY_KPSLASH:
#    command: amixer -q sset Master 5%-
    inject_keys: KEY_VOLUMEDOWN

  KEY_KPASTERISK:
#    command: amixer -q sset Master 5%+
    inject_keys: KEY_VOLUMEUP



  KEY_KPMINUS:
    inject_keys: KEY_RIGHTMETA KEY_S


  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W



  KEY_KP7:
    plugin: gnome
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop

  KEY_KP8:
    plugin: gnome
    # Special, to raise all Chromium-browser window
    # command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    # command: raise chromium chromium.Chromium
    # command: raise vivaldi-stable Vivaldi-stable
    command: raise firefox Firefox
    #command: raise_all firefox Navigator.Firefox https://www.youtube.com
    #command: raise opera Opera
  #KEY_LEFTCTRL KEY_KP8:
  CTRL KEY_KP8:
    plugin: gnome
    # Raise only Firefox with youtube player
    command: raise chromium-browser chromium.Chromium
    # command: raise echo Navigator.Firefox YouTube
    # command: raise firefox Navigator.Firefox
    # YouTube - Mozilla Firefox

  KEY_KP9:
    plugin: gnome
    command: raise pycharm jetbrains-pycharm
    # command: raise wing7.0 N/A Wing
  CTRL KEY_KP9:
    plugin: gnome
    command: raise /opt/sublime_text/sublime_text Sublime_text
  ALT KEY_KP9:
    plugin: gnome
    command: raise inkscape Inkscape
    # command: raise wing-personal6.1 N/A Wing
  # SHIFT KEY_KP9:
  #   plugin: gnome
  #   command: raise /opt/sublime_text/sublime_text sublime_text.Sublime_text
  META KEY_KP9:
    plugin: gnome
    command: raise atom atom.Atom



  KEY_KP4:
    plugin: gnome
    command: raise skype Skype

  KEY_KP5:
    plugin: gnome
    command: raise gnome-control-center gnome-control-center

  KEY_KP6:
    plugin: gnome
    command: raise teams Teams


  CTRL KEY_KP6:
    plugin: gnome
    command: raise goldendict GoldenDict
#  KEY_RIGHTCTRL KEY_KP6:
#    plugin: gnome
#    command: raise goldendict goldendict.GoldenDict




  KEY_KP1:
    plugin: gnome
    command: raise relanotes Relanotes
  CTRL KEY_KP1:
    plugin: gnome
    command: raise relacalc relacalc.py
#  KEY_RIGHTCTRL KEY_KP1:
#    plugin: gnome
#    command: raise relacalc Relacalc

  KEY_KP2:
    plugin: gnome
    command: raise gnome-terminal Gnome-terminal

  KEY_KP3:
    plugin: gnome
    command: raise nautilus Org.gnome.Nautilus




  KEY_KP0:
    plugin: gnome
    command: minimize

  KEY_KPDOT:
    plugin: gnome
    command: raise gedit org.gnome.gedit
    # command: raise /opt/sublime_text/sublime_text Sublime_text



  KEY_KPENTER:
    plugin: gnome
    command: close
















Logitech Gaming Mouse G600:
  #device: /dev/input/event8
  name: Logitech Gaming Mouse G600 Keyboard
  capabilities: keyboard

  # G15
  # KEY_7:
  KEY_LEFTCTRL KEY_LEFTSHIFT KEY_F5:
    plugin: gnome
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop


  # G16
  # KEY_8:
  KEY_LEFTCTRL KEY_LEFTSHIFT KEY_F6:
    plugin: gnome
    # Special, to raise all Chromium-browser window
    # command: raise chromium-browser Chromium-browser
    command: raise firefox Firefox
    # command: raise vivaldi-stable Vivaldi-stable



  # G17
  KEY_9:
    plugin: gnome
    # command: raise wing7.0 N/A Wing
    command: raise pycharm jetbrains-pycharm



  # G18
  KEY_0:
    plugin: gnome
    command: raise skype Skype
  KEY_P:
    plugin: gnome
    command: raise relanotes Relanotes


  # G19
  # KEY_MINUS:
  KEY_LEFTCTRL KEY_LEFTSHIFT KEY_F9:
    plugin: gnome
    command: raise gnome-terminal Gnome-terminal

  # G20
  # KEY_EQUAL:
  KEY_LEFTCTRL KEY_LEFTSHIFT KEY_F10:
    plugin: gnome
    command: raise nautilus Org.gnome.Nautilus



#  KEY_LEFTCTRL KEY_W:
#    inject_keys: KEY_LEFTCTRL KEY_W

  KEY_2:
    inject_keys: KEY_LEFTCTRL KEY_F9
  ALT KEY_2:
    command: flameshot gui

  KEY_5:
    plugin: gnome
    command: minimize










Logitech G602 mouse:
  name: Logitech USB Receiver Keyboard
  capabilities: keyboard

  # G4
  KEY_4:
    plugin: gnome
    command: minimize
  # G7
  KEY_7:
    #command: xfdesktop --windowlist
    # inject_keys: KEY_LEFTCTRL KEY_F9
    inject_keys: KEY_RIGHTMETA KEY_S
  ALT KEY_7:
    command: flameshot gui


  # G5
  KEY_5:
    plugin: gnome
    # Special, to raise all Chromium-browser window
    # command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    # command: raise vivaldi-stable Vivaldi-stable
    command: raise firefox Firefox
    #command: raise opera Opera
  CTRL KEY_5:
    plugin: gnome
    command: raise chromium-browser chromium.Chromium
    # Raise only Firefox with youtube player
    # command: raise echo Navigator.Firefox YouTube

  # G8
  KEY_8:
    inject_keys: KEY_RIGHTCTRL KEY_W


  # G6
  KEY_6:
    plugin: gnome
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop

  # G9
  KEY_9:
    plugin: gnome
    command: raise skypeforlinux Skype


  # G10
  ALT KEY_PAGEUP:
    inject_keys: KEY_RIGHTALT KEY_LEFT
  SHIFT KEY_PAGEUP:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_HOME
  # G11
  ALT KEY_PAGEDOWN:
    inject_keys: KEY_RIGHTALT KEY_RIGHT
  SHIFT KEY_PAGEDOWN:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_END




Notebook Keyboard:
  #device: /dev/input/event3
  name: AT Translated Set 2 keyboard
  capabilities: keyboard


  KEY_SCROLLLOCK:
    command: flameshot gui

  KEY_PAUSE:
    plugin: gnome
    command: lock
  CTRL KEY_PAUSE:
    command: systemctl suspend



  KEY_KPSLASH:
#    command: amixer -q sset Master 5%-
    inject_keys: KEY_VOLUMEDOWN

  KEY_KPASTERISK:
#    command: amixer -q sset Master 5%+
    inject_keys: KEY_VOLUMEUP



  KEY_KPMINUS:
    inject_keys: KEY_RIGHTMETA KEY_S


  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W



  KEY_KP7:
    plugin: gnome
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop

  KEY_KP8:
    plugin: gnome
    # Special, to raise all Chromium-browser window
    # command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    # command: raise chromium chromium.Chromium
    # command: raise vivaldi-stable Vivaldi-stable
    command: raise firefox Firefox
    #command: raise_all firefox Navigator.Firefox https://www.youtube.com
    #command: raise opera Opera
  #KEY_LEFTCTRL KEY_KP8:
  CTRL KEY_KP8:
    plugin: gnome
    # Raise only Firefox with youtube player
    command: raise chromium-browser chromium.Chromium
    # command: raise echo Navigator.Firefox YouTube
    # command: raise firefox Navigator.Firefox
    # YouTube - Mozilla Firefox

  KEY_KP9:
    plugin: gnome
    command: raise pycharm jetbrains-pycharm
    # command: raise wing7.0 N/A Wing
  CTRL KEY_KP9:
    plugin: gnome
    command: raise /opt/sublime_text/sublime_text Sublime_text
  ALT KEY_KP9:
    plugin: gnome
    command: raise inkscape Inkscape
    # command: raise wing-personal6.1 N/A Wing
  # SHIFT KEY_KP9:
  #   plugin: gnome
  #   command: raise /opt/sublime_text/sublime_text sublime_text.Sublime_text
  META KEY_KP9:
    plugin: gnome
    command: raise atom atom.Atom



  KEY_KP4:
    plugin: gnome
    command: raise skype Skype

  KEY_KP5:
    plugin: gnome
    command: raise gnome-control-center gnome-control-center

  KEY_KP6:
    plugin: gnome
    #command: raise okular okular
    command: raise teams Teams


  CTRL KEY_KP6:
    plugin: gnome
    command: raise goldendict GoldenDict
#  KEY_RIGHTCTRL KEY_KP6:
#    plugin: gnome
#    command: raise goldendict goldendict.GoldenDict




  KEY_KP1:
    plugin: gnome
    command: raise relanotes Relanotes
  CTRL KEY_KP1:
    plugin: gnome
    command: raise relacalc relacalc.py
#  KEY_RIGHTCTRL KEY_KP1:
#    plugin: gnome
#    command: raise relacalc Relacalc

  KEY_KP2:
    plugin: gnome
    command: raise gnome-terminal Gnome-terminal

  KEY_KP3:
    plugin: gnome
    command: raise nautilus Org.gnome.Nautilus




  KEY_KP0:
    plugin: gnome
    command: minimize

  KEY_KPDOT:
    plugin: gnome
    command: raise gedit org.gnome.gedit
    # command: raise /opt/sublime_text/sublime_text Sublime_text


  KEY_KPENTER:
    plugin: gnome
    command: close


