

Logitech MX Master Mouse:
  name: Logitech MX Master 3
  capabilities: mouse
  # uinput_dev: duplication

  # #BTN_EXTRA:
  # _276:
  #   #command: flameshot gui
  #   inject_keys: KEY_LEFTMETA

  # # BTN_SIDE:
  # _275:
  #   #command: flameshot gui
  #   inject_keys: KEY_LEFTMETA KEY_H


  # up
  REL_HWHEEL:-1:
    inject_keys: KEY_LEFTCTRL KEY_F9
  REL_HWHEEL:-1,-1:
    inject_keys: KEY_LEFTCTRL KEY_F9

  REL_HWHEEL:-1,-1,-1:
    plugin: wmctrl
    command: raise firefox Firefox
  REL_HWHEEL:-1,-1,-1,-1:
    plugin: wmctrl
    command: raise firefox Firefox


  REL_HWHEEL:-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise slack Slack
  REL_HWHEEL:-1,-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise slack Slack
  REL_HWHEEL:-1,-1,-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise slack Slack


  REL_HWHEEL:-1,-1,-1,-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise ~/bin/Telegram/Telegram TelegramDesktop
  REL_HWHEEL:-1,-1,-1,-1,-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise ~/bin/Telegram/Telegram TelegramDesktop
  REL_HWHEEL:-1,-1,-1,-1,-1,-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise ~/bin/Telegram/Telegram TelegramDesktop
  REL_HWHEEL:-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1:
    plugin: wmctrl
    command: raise ~/bin/Telegram/Telegram TelegramDesktop



  # down
  REL_HWHEEL:1:
      plugin: xdotool
      command: minimize
  REL_HWHEEL:1,1:
      plugin: xdotool
      command: minimize


  REL_HWHEEL:1,1,1:
      inject_keys: KEY_LEFTCTRL KEY_W
  REL_HWHEEL:1,1,1,1:
      inject_keys: KEY_LEFTCTRL KEY_W
  REL_HWHEEL:1,1,1,1,1:
      inject_keys: KEY_LEFTCTRL KEY_W
  REL_HWHEEL:1,1,1,1,1,1:
      inject_keys: KEY_LEFTCTRL KEY_W


  REL_HWHEEL:1,1,1,1,1,1,1,1,1:
      inject_keys: KEY_LEFTALT KEY_F4
  REL_HWHEEL:1,1,1,1,1,1,1,1,1,1:
      inject_keys: KEY_LEFTALT KEY_F4
  REL_HWHEEL:1,1,1,1,1,1,1,1,1,1,1:
      inject_keys: KEY_LEFTALT KEY_F4
  REL_HWHEEL:1,1,1,1,1,1,1,1,1,1,1,1:
      inject_keys: KEY_LEFTALT KEY_F4



  # # 6
  # REL_HWHEEL:

  #   # up:
  #   -1:


  #   -1, -1:
  #   #

  #   #down:
  #   1:
  #   ##

  #   1, 1:






Logitech G710 Keyboard:
  #device: /dev/input/event9
  name: Logitech Logitech G710 Keyboard
  capabilities: keyboard
  include: ./configs/includes/typical_keyboard_kde.yml




Logitech G413 keyboard:
  name: Logitech G413 Carbon Mechanical Gaming Keyboard
  capabilities: keyboard
  include: ./configs/includes/typical_keyboard_kde.yml








Logitech Gaming Mouse G600:
  #device: /dev/input/event8
  name: Logitech Gaming Mouse G600 Keyboard
  capabilities: keyboard

  # G15
  KEY_7:
    plugin: wmctrl
    # command: raise telegram-desktop TelegramDesktop
    command: raise ~/bin/Telegram/Telegram TelegramDesktop


  # G16
  KEY_8:
    plugin: wmctrl
    # Special, to raise all Chromium-browser window
    #command: raise chromium-browser Chromium-browser
    command: raise firefox Navigator.Firefox
    # command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable



  # G17
  KEY_9:
    plugin: wmctrl
    # command: raise wing7.0 N/A Wing
    command: raise pycharm jetbrains-pycharm



  # G18
  KEY_0:
    plugin: wmctrl
    command: raise skype skype.Skype
  KEY_P:
    plugin: wmctrl
    command: raise relanotes relanotes.py.Relanotes


  # G19
  KEY_MINUS:
    plugin: wmctrl
    command: raise konsole konsole.konsole

  # G20
  KEY_EQUAL:
    plugin: wmctrl
    command: raise dolphin dolphin.dolphin


#  KEY_LEFTCTRL KEY_W:
#    inject_keys: KEY_LEFTCTRL KEY_W

  KEY_2:
    inject_keys: KEY_LEFTCTRL KEY_F9
  ALT KEY_2:
    command: flameshot gui

  KEY_5:
    plugin: xdotool
    command: minimize












Notebook Keyboard:
  #device: /dev/input/event3
  name: AT Translated Set 2 keyboard
  capabilities: keyboard
  include: ./configs/includes/typical_keyboard_kde.yml

