# Be careful with indent in beginning of line!
#
# One KEY defining block limited to 1024 bytes
#
# In section - any name of your device you like.
## EXAMPLE OF SUBSECTION
## This is CTRL+R for example
#
# KEY_LEFTCTRL KEY_R:
# inject_keys=KEY_RIGHTCTRL KEY_W
# run_command=ls -la


Logitech G413 keyboard:
  device: /dev/input/event3


  KEY_PAUSE:
    plugin: gnome
    command: lock
  KEY_LEFTCTRL KEY_PAUSE:
    command: systemctl suspend
  KEY_RIGHTCTRL KEY_PAUSE:
    command: systemctl suspend

  KEY_KP6:
    plugin: gnome
    command: raise opera Opera

  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W

  KEY_KP0:
    plugin: gnome
    command: minimize

  KEY_KPENTER:
    plugin: gnome
    command: close

  KEY_KPMINUS:
    inject_keys: KEY_RIGHTMETA KEY_S



Logitech G602 mouse:
  device: /dev/input/event9

  # G4
  KEY_LEFTSHIFT KEY_F4:
    plugin: gnome
    command: minimize
  # G7
  ALT KEY_LEFTMETA KEY_S:
    command: notify-send Alt+Meta+S


  # G5
  KEY_LEFTSHIFT KEY_F5:
    plugin: gnome
    command: raise opera Opera
  # G8
  KEY_LEFTSHIFT KEY_F8:
    inject_keys: KEY_RIGHTCTRL KEY_W


  # G6
  KEY_LEFTSHIFT KEY_F6:
    plugin: gnome
    command: raise telegram-desktop TelegramDesktop
  # G9
  KEY_LEFTSHIFT KEY_F9:
    plugin: gnome
    command: raise skypeforlinux Skype


  # G10
  ALT KEY_PAGEUP:
    inject_keys: KEY_RIGHTALT KEY_LEFT
  SHIFT KEY_PAGEUP:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_HOME
  # G11
  ALT KEY_PAGEDOWN:
    inject_keys: KEY_RIGHTALT KEY_RIGHT
  SHIFT KEY_PAGEDOWN:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_END



Razer Nostromo:
  device: /dev/input/event6

  KEY_RIGHTSHIFT KEY_F6:
    inject_keys: KEY_R

  # 01
  KEY_TAB:
    inject_keys: KEY_RIGHTCTRL KEY_W
  # 02
  KEY_Q:
    plugin: gnome
    command: raise telegram-desktop TelegramDesktop
  # 03
  KEY_W:
    plugin: gnome
    command: raise opera Opera
  # 04
  KEY_E:
    command: notify-send Button-04
  # 05
  KEY_R:
    inject_keys: KEY_PAGEUP

  # 06
  KEY_CAPSLOCK:
    plugin: gnome
    command: close
  # 07
  KEY_A:
    plugin: gnome
    command: raise skypeforlinux Skype
  # 08
  KEY_S:
    command: notify-send Button-08
  # 09
  KEY_D:
    command: notify-send Button-09
  # 10
  KEY_F:
    inject_keys: KEY_PAGEDOWN

  # 11
  KEY_LEFTSHIFT:
    plugin: gnome
    command: minimize

  # 12
  KEY_Z:
    plugin: gnome
    command: raise relanotes Relanotes
  # 13
  KEY_X:
    plugin: gnome
    command: raise gnome-terminal Gnome-terminal
  # 14
  KEY_C:
    plugin: gnome
    command: raise nautilus Nautilus

  # 15
  KEY_SPACE:
    inject_keys: KEY_LEFTMETA KEY_S

  # Round button (above joystick)
  KEY_LEFTALT:
    inject_keys: KEY_LEFTCTRL

  # Joystick:
#    KEY_DOWN:
#        command: notify-send Button-Down
#    KEY_RIGHT:
#        inject_keys: KEY_PAGEDOWN
#    KEY_UP:
#        command: notify-send Button-Up
#    KEY_LEFT:
#        inject_keys: KEY_PAGEUP
