Logitech G413 keyboard:
#  device: /dev/input/event4
  name: Logitech G413 Carbon Mechanical Gaming Keyboard
  capabilities: keyboard

#  META KEY_S:
#    #inject_keys: KEY_LEFTCTRL KEY_LEFTALT KEY_DOWN
#    plugin: wmctrl
#    command: raise nemo nemo.Nemo

  KEY_SCROLLLOCK:
    command: flameshot gui

  KEY_PAUSE:
    command: cinnamon-screensaver-command -l
    # to lock and disable moinitor:
    # cinnamon-screensaver-command -l; xset dpms force off;
  CTRL KEY_PAUSE:
    command: systemctl suspend -i
#  KEY_RIGHTCTRL KEY_PAUSE:
#    command: systemctl suspend -i


  KEY_KP7:
    plugin: wmctrl
    command: raise telegram-desktop TelegramDesktop

  KEY_KP8:
    plugin: wmctrl
    # Special, to raise all Chromium-browser window
    #command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    #command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable
    command: raise firefox Navigator.Firefox
    #command: raise_all firefox Navigator.Firefox https://www.youtube.com
    #command: raise opera Opera
  #KEY_LEFTCTRL KEY_KP8:
  CTRL KEY_KP8:
    plugin: wmctrl
    # Raise only Firefox with youtube player
    command: raise echo Navigator.Firefox https://www.youtube.com
    # YouTube - Mozilla Firefox

  KEY_KP9:
    plugin: wmctrl
    command: raise pycharm jetbrains-pycharm
  CTRL KEY_KP9:
    plugin: wmctrl
    command: raise inkscape inkscape.Inkscape
  ALT KEY_KP9:
    plugin: wmctrl
    command: raise wing-personal6.1 N/A Wing


  KEY_KP4:
    plugin: wmctrl
    command: raise skype Skype

  KEY_KP5:
    plugin: wmctrl
    command: raise cinnamon-settings cinnamon-settings

  KEY_KP6:
    plugin: wmctrl
    command: raise okular Okular
  CTRL KEY_KP6:
    plugin: wmctrl
    command: raise goldendict goldendict.GoldenDict
#  KEY_RIGHTCTRL KEY_KP6:
#    plugin: wmctrl
#    command: raise goldendict goldendict.GoldenDict




  KEY_KP1:
    plugin: wmctrl
    command: raise relanotes Relanotes
  CTRL KEY_KP1:
    plugin: wmctrl
    command: raise relacalc Relacalc
#  KEY_RIGHTCTRL KEY_KP1:
#    plugin: wmctrl
#    command: raise relacalc Relacalc

  KEY_KP2:
    plugin: wmctrl
    command: raise gnome-terminal Gnome-terminal

  KEY_KP3:
    plugin: wmctrl
    command: raise nemo nemo.Nemo


  KEY_KPDOT:
    plugin: wmctrl
    command: raise xed Xed


  KEY_KPSLASH:
    command: amixer -q sset Master 5%-

  KEY_KPASTERISK:
    command: amixer -q sset Master 5%+



  KEY_KPPLUS:
    # In subsection - keys, must be handled
    # And what we must do with it below.
    inject_keys: KEY_RIGHTCTRL KEY_W

  KEY_KP0:
    plugin: xdotool
    command: minimize

  KEY_KPENTER:
    plugin: wmctrl
    command: close

  KEY_KPMINUS:
    #inject_keys: KEY_RIGHTMETA KEY_S
    inject_keys: KEY_LEFTCTRL KEY_LEFTALT KEY_DOWN



Logitech G602 mouse:
#  device: /dev/input/event9
  name: Logitech USB Receiver
  capabilities: keyboard

  # G4
  KEY_4:
    plugin: xdotool
    command: minimize
  # G7
  KEY_7:
    inject_keys: KEY_LEFTCTRL KEY_LEFTALT KEY_DOWN
  ALT KEY_7:
    command: flameshot gui


  # G5
  KEY_5:
    plugin: wmctrl
    # Special, to raise all Chromium-browser window
    #command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    #command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable
    command: raise firefox Navigator.Firefox
    #command: raise opera Opera
  # G8
  KEY_8:
    inject_keys: KEY_RIGHTCTRL KEY_W


  # G6
  KEY_6:
    plugin: wmctrl
    command: raise telegram-desktop TelegramDesktop
  # G9
  KEY_9:
    plugin: wmctrl
    command: raise skypeforlinux Skype


  # G10
  ALT KEY_PAGEUP:
    inject_keys: KEY_RIGHTALT KEY_LEFT
  SHIFT KEY_PAGEUP:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_HOME
  # G11
  ALT KEY_PAGEDOWN:
    inject_keys: KEY_RIGHTALT KEY_RIGHT
  SHIFT KEY_PAGEDOWN:
    # command: notify-send Shift-PageUp
    inject_keys: KEY_END



Razer Nostromo:
#  device: /dev/input/event6
  name: Razer Razer Nostromo
  capabilities: keyboard

  KEY_RIGHTSHIFT KEY_F6:
    inject_keys: KEY_R

  # 01
  KEY_TAB:
    inject_keys: KEY_RIGHTCTRL KEY_W
  # 02
  KEY_Q:
    command: notify-send Button-02
  # 03
  KEY_W:
    plugin: wmctrl
    # Special, to raise all Chromium-browser window
    #command: raise chromium-browser Chromium-browser
    #command: raise chromium-browser chromium-browser.Chromium-browser
    #command: raise vivaldi-stable vivaldi-stable.Vivaldi-stable
    command: raise firefox Navigator.Firefox
    #command: raise opera Opera
  # 04
  KEY_E:
    #command: notify-send Button-04
    plugin: wmctrl
    command: raise telegram-desktop TelegramDesktop

  # 05
  KEY_R:
    inject_keys: KEY_PAGEUP

  # 06
  KEY_CAPSLOCK:
    plugin: wmctrl
    command: close
  # 07
  KEY_A:
    #plugin: wmctrl
    #command: raise skypeforlinux Skype
    command: notify-send Button-07
  # 08
  KEY_S:
    command: notify-send Button-08
  # 09
  KEY_D:
    #command: notify-send Button-09
    plugin: wmctrl
    command: raise skypeforlinux Skype

  # 10
  KEY_F:
    inject_keys: KEY_PAGEDOWN

  # 11
  KEY_LEFTSHIFT:
    plugin: xdotool
    command: minimize

  # 12
  KEY_Z:
    plugin: wmctrl
    command: raise nemo nemo.Nemo
  # 13
  KEY_X:
    plugin: wmctrl
    command: raise gnome-terminal Gnome-terminal
  # 14
  KEY_C:
    plugin: wmctrl
    command: raise relanotes Relanotes

  # 15
  KEY_SPACE:
    inject_keys: KEY_LEFTCTRL KEY_LEFTALT KEY_DOWN

  # Round button (above joystick)
  KEY_LEFTALT:
    inject_keys: KEY_LEFTCTRL

  # Joystick:
#    KEY_DOWN:
#        command: notify-send Button-Down
#    KEY_RIGHT:
#        inject_keys: KEY_PAGEDOWN
#    KEY_UP:
#        command: notify-send Button-Up
#    KEY_LEFT:
#        inject_keys: KEY_PAGEUP
